default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: rslira
  password: intdigital4112
  host:     <%= ENV['IP'] %>

development:
  <<: *default
  database: sssmartads_development

test:
  <<: *default
  database: sssmartads_test

production:
  <<: *default
  database: sssmartads_production
